name: online_exams
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  #? Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  #? Helpers
  animate_do: ^4.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  toastification: ^2.0.0
  
  #? Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  
  #? Storage
  shared_preferences: ^2.5.2
  
  #? Image
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  #? Permission
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.0
  connectivity_plus: ^6.1.3
  
  #? State management
  flutter_bloc: ^9.0.0
  #? service locator
  get_it: ^8.0.3
  injectable: ^2.5.0
  
  #? Logger
  logger: ^2.5.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  equatable: ^2.0.7
  regexpattern: ^2.6.0
  

dev_dependencies:
  #? Generator
  #! flutter packages pub run build_runner build
  #! flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.13 
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.5
  
  # Linter
  flutter_lints: ^4.0.0
  
  # Test
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
