// Mocks generated by Mockito 5.4.4 from annotations
// in online_exams/test/features/auth/data/data_sources/auth_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:online_exams/core/api_helper/api_consumer/api_consumer.dart'
    as _i2;
import 'package:online_exams/core/api_helper/api_result/api_result.dart' as _i5;
import 'package:online_exams/features/auth/data/api/api_auth.dart' as _i3;
import 'package:online_exams/features/auth/data/models/request/login_request.dart'
    as _i9;
import 'package:online_exams/features/auth/data/models/request/register_request.dart'
    as _i7;
import 'package:online_exams/features/auth/data/models/response/auth_response.dart'
    as _i6;
import 'package:online_exams/features/auth/data/models/response/forgot_password_response.dart'
    as _i10;
import 'package:online_exams/features/auth/data/models/response/verify_response.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiConsumer_0 extends _i1.SmartFake implements _i2.ApiConsumer {
  _FakeApiConsumer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiAuth extends _i1.Mock implements _i3.ApiAuth {
  MockApiAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiConsumer get apiConsumer => (super.noSuchMethod(
        Invocation.getter(#apiConsumer),
        returnValue: _FakeApiConsumer_0(
          this,
          Invocation.getter(#apiConsumer),
        ),
      ) as _i2.ApiConsumer);

  @override
  set apiConsumer(_i2.ApiConsumer? _apiConsumer) => super.noSuchMethod(
        Invocation.setter(
          #apiConsumer,
          _apiConsumer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.ApiResult<_i6.AuthResponse>> register(
          _i7.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i4.Future<_i5.ApiResult<_i6.AuthResponse>>.value(
            _i8.dummyValue<_i5.ApiResult<_i6.AuthResponse>>(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i6.AuthResponse>>);

  @override
  _i4.Future<_i5.ApiResult<_i6.AuthResponse>> login(
          _i9.LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i4.Future<_i5.ApiResult<_i6.AuthResponse>>.value(
            _i8.dummyValue<_i5.ApiResult<_i6.AuthResponse>>(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i6.AuthResponse>>);

  @override
  _i4.Future<_i5.ApiResult<_i10.ForgotPasswordResponse>> forgotPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i10.ForgotPasswordResponse>>.value(
                _i8.dummyValue<_i5.ApiResult<_i10.ForgotPasswordResponse>>(
          this,
          Invocation.method(
            #forgotPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i10.ForgotPasswordResponse>>);

  @override
  _i4.Future<_i5.ApiResult<_i11.VerifyResponse>> verify(String? resetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify,
          [resetCode],
        ),
        returnValue: _i4.Future<_i5.ApiResult<_i11.VerifyResponse>>.value(
            _i8.dummyValue<_i5.ApiResult<_i11.VerifyResponse>>(
          this,
          Invocation.method(
            #verify,
            [resetCode],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i11.VerifyResponse>>);
}
